
#tasks:
#- init: ./mvnw package -DskipTests
#  command: java -jar target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  visibility: public
- port: 5005
  onOpen: open-preview
  #visibility: public
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
